Add hgat example
dmlc/dgl pull request #2486
Opened 2021-01-04 07:51 UTC by Ericcsr

## Description
Added example of hGAT, hasn't reached state of art performance.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR

## Changes

2021-01-10 12:45 UTC, BarclayII commented
@Ericcsr Which part of the computation does not support gradient?

2021-01-10 15:31 UTC, Ericcsr commented
Currently, all part should support gradient flow, and it has been tested

2021-01-10 15:31 UTC, Ericcsr commented
> @Ericcsr Which part of the computation does not support gradient?

Currently, all part should support gradient, which has been tested

2021-01-11 03:05 UTC, mufeili commented
Can you also add entries in examples/README.md for indexing?

2021-01-14 02:51 UTC, sneakerkg commented
@Ericcsr There're some empty files like: benchmarks/benchmarks/__init__.py , please have a clean.

2021-01-14 04:22 UTC, sneakerkg commented
Let's change the folder name to hardgat. hgat might be confused with heterogenous gat.

2021-01-14 05:12 UTC, sneakerkg requested changes

2021-01-14 05:36 UTC, Ericcsr commented on examples/pytorch/hgat/hgat.py
> +                 out_dim=7,
The 97 feature version is applied for graph classification task, I implement node classification.

2021-01-14 05:45 UTC, Ericcsr commented on examples/README.md
> +| [MixHop: Higher-Order Graph Convolutional Architectures via Sparsified Neighborhood Mixing](#mixhop)                     | :heavy_check_mark:  |                                  |
May be due to an additional space or tab located some where by accident

2021-01-14 05:53 UTC, Ericcsr commented on examples/pytorch/hgat/train.py
> +Graph Attention Networks in DGL using SPMV optimization.
Sure

2021-01-14 05:53 UTC, Ericcsr commented on examples/pytorch/hgat/train_ppi.py
> +"""
OK,sure

2021-01-14 05:53 UTC, Ericcsr commented on examples/pytorch/hgat/hgao.py
> +from dgl.nn.pytorch import edge_softmax, GATConv
OK, sure

2021-01-14 08:54 UTC, Ericcsr commented on examples/pytorch/hgat/hgao.py
> +        # TODO: Maybe need exactly same initialization
Same initialization technique xavier

2021-01-14 16:04 UTC, sneakerkg requested changes

2021-01-14 16:04 UTC, sneakerkg commented on examples/README.md
> +| [MixHop: Higher-Order Graph Convolutional Architectures via Sparsified Neighborhood Mixing](#mixhop)                     | :heavy_check_mark:  |                                  |
There're conflicts with master now. Please rebase remote master. The issue for those empty files might be resolved as well.

2021-01-15 03:53 UTC, yzh119 commented on examples/pytorch/hardgat/hgao.py
> +            graph.apply_edges(self.n2e_weight_transfer)
Please use `dgl.function.copy_u` instead.

2021-01-15 08:30 UTC, sneakerkg approved these changes

2021-01-15 08:58 UTC, merged