[Feature] Add reverse edges in CitationGraphDataset
dmlc/dgl pull request #2588
Opened 2021-01-28 09:25 UTC by JuliaSun623

## Description
This pr adds optional parameter "reverse_edge (bool)" in CitetationGraphDataset, determining whether to reverse edges in graph. Related issue: https://github.com/dmlc/dgl/issues/2580

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2021-01-29 02:26 UTC, HuXiangkun requested changes

2021-01-29 05:57 UTC, JuliaSun623 reviewed
reviewed

2021-01-29 09:31 UTC, hetong007 requested changes

2021-01-29 09:31 UTC, hetong007 commented on python/dgl/data/dgl_dataset.py
> +    reverse_edge: bool
This option is only valid for citation graphs, we won't add it to the base class.

2021-01-29 15:38 UTC, VoVAllen commented on python/dgl/data/citation_graph.py
> +        if self.reverse_edge == True:
```suggestion
        if self.reverse_edge:
```

2021-01-31 01:35 UTC, hetong007 approved these changes
LGTM

2021-02-02 07:51 UTC, classicsong approved these changes
LGTM

2021-02-02 07:52 UTC, merged