[Example] Temporal Graph Neural Network
dmlc/dgl pull request #2636
Opened 2021-02-05 13:18 UTC by Ericcsr

## Description

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2021-02-19 06:37 UTC, sneakerkg requested changes

2021-02-19 06:37 UTC, sneakerkg commented on examples/pytorch/tgn/data.py
> +# Probe ahead to get the valid spliting point
What is a splitting point?

2021-02-19 06:37 UTC, sneakerkg commented on examples/pytorch/tgn/data.py
> +    def __init__(self,parent,NIDdict=None):
Need comments on parent and NIDdict.

2021-02-19 06:37 UTC, sneakerkg commented on examples/pytorch/tgn/data.py
> +        np.random.seed(2020)
Usually random seed is set at main.py file.

2021-02-19 06:37 UTC, sneakerkg commented on examples/pytorch/tgn/data.py
> +        self.nn_mask_g   = dgl.node_subgraph(self.g,non_new_node_idxs)
What is the 'nn' here means?

2021-02-19 06:37 UTC, sneakerkg commented on examples/pytorch/tgn/data.py
> +        src_list = graph.edges()[0][self.batch_cnt*self.batch_size:min((self.batch_cnt+1)*self.batch_size,graph.num_edges())]
Line is too long. Need refactoring.

2021-02-19 06:37 UTC, sneakerkg commented on examples/pytorch/tgn/modules.py
> +    self.w.weight = torch.nn.Parameter((torch.from_numpy(1 / 10 ** np.linspace(0, 9, dimension)))
Why this formula?

2021-02-19 06:37 UTC, sneakerkg commented on examples/pytorch/tgn/modules.py
> +    def __init__(self,updater_type, memory, e_feat_dim, temporal_dim):
Comments on each parameter.

2021-02-19 06:37 UTC, sneakerkg commented on examples/pytorch/tgn/modules.py
> +        self.message_dim = memory_dim+memory_dim+e_feat_dim+temporal_dim
Why message_dim is computed like this?

2021-02-19 06:37 UTC, sneakerkg commented on examples/pytorch/tgn/modules.py
> +        self.memory = memory
Duplicate with line 105.

2021-02-19 06:37 UTC, sneakerkg commented on examples/pytorch/tgn/modules.py
> +        g.ndata['timestamp'] = self.memory.last_update_t[g.ndata[dgl.NID]]
This mapping is confusing.

2021-02-19 06:37 UTC, sneakerkg commented on examples/pytorch/tgn/modules.py
> +        return rst
Usually we need an empty line at the end of each file.

2021-02-19 06:37 UTC, sneakerkg commented on logging.txt
> +Hello World!!
Remove this file.

2021-02-19 06:37 UTC, sneakerkg commented on examples/pytorch/tgn/train_gru.py
> +import dgl
GRU and memory are trained separately?

2021-02-26 05:06 UTC, sneakerkg commented on examples/pytorch/tgn/data_preprocess.py
> +    return TemporalDataset('reddit')
In some python format guide, we can add an empty line at the end of each file.

2021-02-26 05:06 UTC, sneakerkg commented on examples/pytorch/tgn/logging.txt
> +Epoch: 0; Training Loss: 38642.09296107292 | Validation AP: 0.988 AUC: 0.991
Delete logging file.

2021-02-26 05:06 UTC, sneakerkg commented on examples/pytorch/tgn/train.py
> +from dataloading import FastTemporalEdgeCollator,NegativeSampler,FastTemporalSampler,TemporalEdgeDataLoader,temporal_sort,TemporalSampler,TemporalEdgeCollator
If you import a lot of things from a file, a suggested way is:
from utils import (AA, BB, CC,
                             DD, EE, FF)

2021-02-26 05:06 UTC, sneakerkg commented on logging.txt
> +Hello World!!
We still have this file?

2021-03-11 12:22 UTC, WangXuhongCN commented on examples/pytorch/tgn/data_preprocess.py
> +def reindex(df, bipartite=True):
perhaps we need a non-bipartite reindex module, like my [APAN code ](https://github.com/WangXuhongCN/APAN/blob/0474a5a5bc2729f0550d8454be6772f1ff92e8b7/preprocess/preprocess_csv.py#L104)

2021-03-22 10:56 UTC, sneakerkg requested changes

2021-03-22 10:56 UTC, sneakerkg commented on examples/pytorch/tgn/dataloading.py
> +    """ TemporalEdgeDataLoader is a iteratable object to generate blocks for temporal embedding
a -> an

2021-03-22 10:56 UTC, sneakerkg commented on examples/pytorch/tgn/dataloading.py
> +    Temporal and computationally depending subgraph.
Temporal -> temporal

2021-03-22 10:56 UTC, sneakerkg commented on examples/pytorch/tgn/dataloading.py
> +        graph to be sampled here it which only exist to provide feature and data reference
grammer

2021-03-22 10:56 UTC, sneakerkg commented on examples/pytorch/tgn/dataloading.py
> +# https://github.com/rusty1s/pytorch_geometric
Please given specific file name here. We just don't want to point to the whole PyG repo :)

2021-03-22 10:56 UTC, sneakerkg commented on examples/pytorch/tgn/dataloading.py
> +        g = dgl.in_subgraph(g, seed_nodes)  # 只包含seed_node的g（不考虑邻居吗？）
Use English comments.

2021-03-22 10:56 UTC, sneakerkg commented on examples/pytorch/tgn/logging.txt
> +Epoch: 0; Training Loss: 43824.699464440346 | Validation AP: 0.977 AUC: 0.984
Remove this file.

2021-03-22 10:56 UTC, sneakerkg commented on examples/pytorch/tgn/tgn.py
> +import copy
Put this import to the first line.

2021-03-22 10:56 UTC, sneakerkg commented on logging.txt
> +Hello World!!
Seems this file still exists.

2021-03-22 15:07 UTC, Ericcsr commented on examples/pytorch/tgn/dataloading.py
> +    Please refers to examples/pytorch/tgn/train.py
Simple Mode can, others cannot

2021-03-22 15:19 UTC, sneakerkg approved these changes

2021-03-23 00:57 UTC, merged