[Example] TAHIN
dmlc/dgl pull request #2864
Opened 2021-04-23 10:45 UTC by KounianhuaDu

## Description
This is the implementation of the TAHIN module proposed in "A Heterogeneous Information Network based Cross DomainInsurance Recommendation System for Cold Start Users".

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2021-04-23 10:46 UTC, KounianhuaDu commented
@zhjwy9343 
In addition, should I send an email to the author with the pr link attached?

2021-05-31 08:10 UTC, zhjwy9343 requested changes

2021-05-31 08:10 UTC, zhjwy9343 commented on examples/pytorch/TAHIN/readme.md
> +This DGL example implements the TAHIN module proposed in the paper [HCDIR](https://arxiv.org/pdf/2007.15293.pdf). Since the code and dataset have not been published yet, we implement its main idea an
emperiment -> experiment

2021-06-03 05:54 UTC, zhjwy9343 approved these changes
LGTM

2021-06-03 06:56 UTC, zhjwy9343 approved these changes
LGTM

2021-06-03 08:03 UTC, merged