[NN] GCNII model added <https://arxiv.org/pdf/2007.02133.pdf>
dmlc/dgl pull request #2874
Opened 2021-04-26 10:35 UTC by kyawlin

GCNII model added

## Description

## Checklist
Please feel free to remove inapplicable items for your PR.
- [X] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [X] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [X] Code is well-documented
- [X] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2021-04-26 10:35 UTC, VoVAllen commented
To trigger regression tests: 
 - `@dgl-bot run [instance-type] [which tests] [compare-with-branch]`; 
 For example: `@dgl-bot run g4dn.4xlarge all dmlc/master` or `@dgl-bot run c5.9xlarge kernel,api dmlc/master`

2021-04-30 07:15 UTC, sneakerkg commented
@VoVAllen May I bother you ask Yongyi to have a check on this PR? I believe GCNII if from their group.

2021-04-30 07:17 UTC, sneakerkg requested changes
@kyawlin Thanks for contributing to DGL. I may bother you also adding the module info into: https://github.com/dmlc/dgl/blob/master/docs/source/api/python/nn.pytorch.rst  so that our doc  will automatically build for this module.

2021-05-07 03:02 UTC, BarclayII requested changes

2021-05-07 03:02 UTC, BarclayII commented on python/dgl/nn/pytorch/conv/gcn2conv.py
> +            where :math:`D_{in}` is size of input feature, :math:`N` is the number of nodes.
```suggestion
            The input feature of shape
            :math:`(N, D_{in})`
            where :math:`D_{in}` is the size of input feature and :math:`N` is the number of nodes.
```

2021-05-07 03:02 UTC, BarclayII commented on python/dgl/nn/pytorch/conv/gcn2conv.py
> +                it represents the initial feature of shape :math:`(N, D_{in})`
```suggestion
            The initial feature of shape :math:`(N, D_{in})`
```

2021-05-07 03:02 UTC, BarclayII commented on python/dgl/nn/pytorch/conv/gcn2conv.py
> +            Case 1:
```suggestion
```

Or you can add the other cases.

2021-05-07 08:03 UTC, kyawlin commented
thanks.  I will look into those. :)

2021-05-11 12:10 UTC, BarclayII commented
> @BarclayII could you advice me what I should do next regarding this pull request?

Could you try addressing each of the comments?  Some of the comments have my suggested edits so you can simply click the "Commit suggestion" button if the edits make sense to you.  For other comments you may need manual editing.  Once done you could click the "resolve conversation" button.  You could also reply in the comments directly if you have questions or if the comment does not make sense.

Thanks!

2021-05-12 08:26 UTC, BarclayII approved these changes
Awesome!  Just a few more edits and we are good to go.

2021-05-12 08:26 UTC, BarclayII commented on python/dgl/nn/pytorch/conv/gcn2conv.py
> +                project_initial_features=True, allow_zero_in_degree=True)
```suggestion
    >>> conv1 = GCN2Conv(3, layer=1, alpha=0.5, \
    ...         project_initial_features=True, allow_zero_in_degree=True)
    >>> conv2 = GCN2Conv(3, layer=2, alpha=0.5, \
    ...         project_initial_features=True, allow_zero_in_degree=True)
```

The line continuations should start with `...` like what you see in Python console.

2021-05-12 08:26 UTC, BarclayII commented on python/dgl/nn/pytorch/conv/gcn2conv.py
> +        \left( (1 - \beta) \mathbf{I} + \beta \mathbf{W} \right)
```suggestion
        \left( (1 - \beta_l) \mathbf{I} + \beta \mathbf{W} \right)
```

2021-05-12 08:26 UTC, BarclayII commented on python/dgl/nn/pytorch/conv/gcn2conv.py
> +    :math:`\beta` is the hyperparameter to tune the strength of identity mapping.
```suggestion
    :math:`\beta_l` is the hyperparameter to tune the strength of identity mapping.
```

2021-05-12 08:31 UTC, BarclayII commented
Also, two more changes required to really expose your module:

1. Add your module in `docs/source/api/python/nn.pytorch.rst`.  You can just copy-paste one of the entries and change the name to your `GCN2Conv`.
2. Add your module in the `__all__` list in `python/dgl/nn/pytorch/conv/__init__.py`.

That goes for your other PR as well.

2021-05-15 07:17 UTC, BarclayII commented
@sneakerkg Do you have more comments?

2021-05-17 02:23 UTC, sneakerkg approved these changes

2021-05-17 02:24 UTC, sneakerkg commented
> @sneakerkg Do you have more comments?

LGTM, thanks.

2021-05-17 02:25 UTC, merged