DGL Enter
dmlc/dgl pull request #3690
Opened 2022-01-26 11:49 UTC by VoVAllen

## Description

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2022-02-13 20:56 UTC, yzh119 requested changes

2022-02-13 20:56 UTC, yzh119 commented on enter/README.md
> +`dgl-ente` currently provides 4 pipelines:
```suggestion
`dgl-enter` currently provides 4 pipelines:
```

2022-02-14 04:40 UTC, yzh119 approved these changes

2022-02-18 03:04 UTC, jermainewang commented on enter/dglenter/pipeline/graphpred/gen.py
> +class NodepredPipeline(PipelineBase):
Consider delete the entire graphpred folder as we are cutting it off. Remember to save it for later develop.

2022-02-18 03:04 UTC, jermainewang commented on enter/dglenter/pipeline/linkpred/gen.py
> +    # early_stop: Optional[EarlyStopConfig] = EarlyStopConfig()
If it's not supported. Remove the option.

2022-02-18 03:06 UTC, jermainewang approved these changes

2022-02-18 06:23 UTC, VoVAllen commented on enter/dglenter/utils/early_stop.py
> +class EarlyStopping:
Will do this in a seperate PR

2022-02-18 07:55 UTC, merged