Edge prediction dataloader for enter
dmlc/dgl pull request #3699
Opened 2022-01-28 11:12 UTC by VoVAllen

## Description

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2022-02-08 07:01 UTC, jermainewang requested changes

2022-02-08 07:01 UTC, jermainewang commented on python/dgl/data/adapter.py
> +        super().__init__(dataset.name + '-as-edgepred', hash_key=(neg_ratio, split_ratio, add_self_loop), **kwargs)
If `hash_key` is designed for proper re-loading. Please help change `AsNodePred` as well. Make sure you've tested them properly.

2022-02-08 07:01 UTC, jermainewang commented on tests/compute/test_data.py
> +    assert ds.get_test_edges()[0][0].shape[0] == 1057
Please add a test for invalid cache.

2022-02-09 07:00 UTC, VoVAllen commented on python/dgl/data/adapter.py
> +def negative_sample(g, num_samples):
It's not guaranteed. Can be less than the num_samples, which is consistent to DGL's negative sample. Here using numpy is just to ensure reproducibility with seed provided.

2022-02-09 07:05 UTC, VoVAllen commented on python/dgl/data/adapter.py
> +                (src[train_pos_idx], dst[train_pos_idx]), num_nodes=self.num_nodes)
But for generated edges, the val_edges and test_edges should be masked out in the training stgae right?

2022-02-09 07:56 UTC, VoVAllen commented on python/dgl/data/adapter.py
> +        if any(s not in self.g.nodes[self.target_ntype].data for s in ["train_mask", "val_mask", "test_mask"]):
fixed

2022-02-09 10:52 UTC, jermainewang commented on python/dgl/data/adapter.py
> +        Indicate how much negative samples to be sampled
How many negative samples(edges) to generate per positive sample(edge).

2022-02-09 10:54 UTC, jermainewang commented on python/dgl/data/adapter.py
>  class AsNodePredDataset(DGLDataset):
Add a `feat_size` property to this class is not a bad idea.

2022-02-09 11:00 UTC, jermainewang commented on python/dgl/data/adapter.py
> +
Only support dataset of homogeneous graphs.

Fix numpy random seed to generate deterministic train/val/test split.

2022-02-09 11:03 UTC, jermainewang approved these changes
Remember to:
* Rename `AsEdgePredDataset` to `AsLinkPredDataset`.
* Add docstring for `val_edges` and `test_edges`.

Otherwise, LGTM

2022-02-11 08:59 UTC, merged