[Feature] enable socket net_type for rpc
dmlc/dgl pull request #3951
Opened 2022-04-24 08:40 UTC by Rhett-Ying

## Description

`socket` is enabled back which was the main rpc backend in `0.7.x`. This is supposed to fix the hang issue mentioned in https://github.com/dmlc/dgl/issues/3881.

Try with below command and it works well with `net_type='socket'`:
`DGL_HOME=/home/ubuntu/workspace/dgl_p0 DGL_LIBRARY_PATH=$DGL_HOME/build PYTHONPATH=.:$DGL_HOME/python:$PYTHONPATH python3 ~/workspace/dgl_p0/tools/launch.py --workspace ~/workspace/dgl_p0/examples/pytorch/graphsage/dist/ --num_trainers 4 --num_samplers 4 --num_servers 4 --part_config data/ogb-product.json --ip_config ~/workspace/ip_config.txt " python3 train_dist.py --graph_name ogb-product --ip_config ~/workspace/ip_config.txt --num_epochs 5 --batch_size 256 --eval_every 5"`
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2022-04-25 07:42 UTC, zheng-da commented
is this the same as reverting the code to use the socket for communication?

2022-04-25 07:45 UTC, Rhett-Ying commented
Almost, though not exactly the same.

2022-04-27 12:21 UTC, jermainewang requested changes

2022-04-27 13:29 UTC, Rhett-Ying commented on python/dgl/distributed/rpc_client.py
> +    rpc.create_sender(MAX_QUEUE_SIZE, 'tensorpipe')
I just realized this cannot be checked as this function is called in a separate process which always expect server is in `tensorpipe` and cannot record or know the server's backend. So I'd like to leave it here.

2022-04-27 14:00 UTC, jermainewang commented on python/dgl/distributed/rpc_server.py
> +                                       "try times via env 'DGL_DIST_MAX_TRY_TIMES'.".format(
Failed to connect to receiver [{}:{}] after {} retries. Please check availability of this target receiver or change the max retry times via 'DGL_DIST_MAX_TRY_TIMES'.

2022-04-27 16:10 UTC, merged