[Fix] Fix compiler warnings - part 1
dmlc/dgl pull request #4051
Opened 2022-05-25 16:49 UTC by TristonC

## Description
This PR fix some compiling errors, such as comparison of integer expressions of different signedness, not referenced variable, etc. 

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change

2022-05-26 22:08 UTC, TristonC commented
Cut it off here  and will make another PR or PRs for the rest warnings. @BarclayII  to review.

2022-05-27 11:08 UTC, BarclayII approved these changes
LGTM except one problem.

2022-06-06 01:45 UTC, jermainewang requested changes
Since @BarclayII  has some further question, add a request change flag to avoid accidental merge.

2022-06-23 03:56 UTC, jermainewang approved these changes

2022-06-23 03:57 UTC, merged