[Dist] enable to specify sort_etype for sample_etype_neighbours
dmlc/dgl pull request #4212
Opened 2022-07-05 04:04 UTC by Rhett-Ying

## Description

follow-up for https://github.com/dmlc/dgl/issues/4150.
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2022-07-05 11:02 UTC, jermainewang requested changes

2022-07-05 11:02 UTC, jermainewang commented on python/dgl/distributed/graph_services.py
> +    sort_etypes = os.environ.get('DGL_SORT_ETYPES', '')
This is really bad practice. Please do not rely on environment variable besides the very entry point. This is very confusing and difficult for others to understand when and where this flag is set. Please pass it down by function argument.

2022-07-05 11:47 UTC, Rhett-Ying commented on python/dgl/distributed/dist_context.py
> +        sort_etypes = os.environ.get('DGL_SORT_ETYPES', '')
Do we have corresponding doc? where is it?

2022-07-05 20:31 UTC, zheng-da commented
the main question is why we should expose the sort_etypes flag to users? if we provide this interface, users need to specify this flag and the graph format correctly. this will be very confusing to users.
we should enable sort_etypes by default based on the graph formats specified by users if the input graph is a heterogeneous graph.

2022-07-06 01:41 UTC, Rhett-Ying commented on python/dgl/distributed/dist_graph.py
> +                    self.client_g, tag=self.client_g.edata[ETYPE], tag_type='edge')
@jermainewang @zheng-da Is sorting like this correct ? Is passing tag with `g.edata[ETYPE]` correct? Do I need to sort the inner edges only?

2022-07-11 09:11 UTC, jermainewang approved these changes

2022-07-11 10:37 UTC, merged