[Feature] Add CUDA Weighted Randomwalk Sampling
dmlc/dgl pull request #4243
Opened 2022-07-12 03:52 UTC by zhenliangqiu

## Description
Add CUDA Weighted Randomwalk sampling.

For a heterogeneous graph, the calculation process is as follows:

> - Traverse each CSR subgraph:   
>> - Use the CSR row offset and probability array to calculate the sum of the probabilities of all seed node neighbors W;  
>> -  Take a random number R;  
>> -  Calculate the random weight sum with W[i]*R;  
>> -  Traverse the neighbors of current seed in [0, degree) with n:  
>>> - Accumulate the weights until the sum is greater than W[i]*R, so the n is the next sampling index.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change

## Changes
Add two functions RandomWalkBiased() and _RandomWalkBiasedKernel() in file: dgl/src/graph/sampling/randomwalks/randomwalk_gpu.cu
 to support biased choice for random walk on GPU.

2022-07-18 06:34 UTC, mufeili commented
Could you take a look? @yaox12

2022-07-19 07:35 UTC, yaox12 requested changes
Generally LGTM. Two comments:
1.  Can you enable GPU support for `RandomWalkWithRestart` and `RandomWalkWithStepwiseRestart` with probabilities? I think your kernel already covers them and only some host-side functions need to update.
2. Can you enable unit tests for biased random walk on GPU? It should be in `tests/compute/test_sampling.py`, and `test_non_uniform_random_walk()` more specifically.

Let @nv-dlasalle @lixiaobai09 have a look.

2022-07-22 03:46 UTC, yaox12 commented on src/graph/sampling/randomwalks/randomwalk_gpu.cu
> +    probs[etype] = prob[etype].Ptr<FloatType>();
`prob[etype]` can be empty.

2022-07-25 01:29 UTC, zhenliangqiu reviewed
@yaox12 Thank you for review and changes !  ^-^

2022-07-26 03:36 UTC, yaox12 approved these changes

2022-07-26 05:42 UTC, merged

2022-10-03 21:17 UTC, mfbalin commented
What datasets were used to debug and test this PR? I am working on a new sampling algorithm PR #4668 as well, but I lack datasets that I can use to test my weighted sampling implementation.