Move mock version of dgl_sparse library to DGL repo
dmlc/dgl pull request #4524
Opened 2022-09-07 17:49 UTC by isratnisa

## Description
Addresses issue https://github.com/dmlc/dgl/issues/4489
This PR is  a duplicate of [PR #4500](https://github.com/dmlc/dgl/pull/4500). The old PR was created on the base repo `dmlc/dgl` (not on a forked repo) by mistake. 

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2022-09-11 06:03 UTC, jermainewang requested changes
Some common issues:
* Please make sure examples in the docstring are complete and their outputs are accurate.
* Please directly print out sparse matrix as much as possible.
* Error messages are not general enough which may confuse users in some cases.

2022-09-11 06:03 UTC, jermainewang commented on tests/mock_sparse/test_elementwise_op_sp.py
> +    out_spMat = v_scalar * A
Missing `A / v_scalar`

2022-09-11 06:04 UTC, jermainewang commented
The unit tests for sparse matrix class are missing in the PR. @isratnisa  @mufeili will you guys do it in another PR?

2022-09-12 14:13 UTC, isratnisa commented on tests/mock_sparse/test_elementwise_op_sp.py
> +def test_sparse_op_sparse(idtype, dtype):
Done.

2022-09-12 14:14 UTC, isratnisa commented on tests/mock_sparse/test_elementwise_op_sp.py
> +        out_torch = eval("A.val " + op + " A.val")
Done.

2022-09-12 14:15 UTC, isratnisa commented on python/dgl/mock_sparse/elementwise_op_sp.py
> +        check_sparsity(A, B)
Added support to add two matrices of different sparsity.

2022-09-12 14:49 UTC, isratnisa commented on docs/source/api/python/dgl.sparse_v0.rst
> +dgl.sparse
Do we want to say `mock_sparse` in the title? The warning section I think takes care of that.

2022-09-12 19:16 UTC, isratnisa commented on python/dgl/mock_sparse/elementwise_op_sp.py
> +
Do we want to use `import *` from `sp_matrix.py`?

2022-09-12 19:24 UTC, isratnisa commented on docs/source/api/python/dgl.sparse_v0.rst
> +`dgl_sparse` is a library for sparse operators that are commonly used in GNN models.
Done.

2022-09-12 19:33 UTC, isratnisa commented on python/dgl/mock_sparse/sp_matrix.py
> +    >>> A.shape
Done.

2022-09-13 01:50 UTC, jermainewang commented on python/dgl/mock_sparse/elementwise_op_sp.py
> +
Yes, you should add `from .xxx import *` in the package `__init__.py` so users can use `dgl.mock_sparse.some_api`.

2022-09-13 01:53 UTC, jermainewang commented on tests/pytorch/mock_sparse/test_elementwise_op_sp.py
> +from dgl.mock_sparse.sp_matrix import SparseMatrix
Users shouldn't import from `dgl.mock_sparse.elementwise_op_sp` or `dgl.mock_sparse.sp_matrix`. They should directly import `dgl.mock_sparse.some_api` or `dgl.mock_sparse.SparseMatrix`. This is an issue related to the `__all__` comment.

2022-09-13 01:53 UTC, jermainewang commented on tests/pytorch/mock_sparse/test_elementwise_op_sp.py
> +def test_sparse_op_sparse(idtype, dtype, op):
Please add a similar test for `dgl.mock_sparse.add(A, B)`, etc. This is to verify that the APIs are correctly exposed.

2022-09-13 01:55 UTC, jermainewang requested changes
Just one last suggestion about the API namespace. Otherwise, LGTM. Will approve afterwards.

2022-09-14 00:54 UTC, jermainewang approved these changes
LGTM

2022-09-14 16:08 UTC, merged