[DistPart] expose timeout config for process group
dmlc/dgl pull request #4532
Opened 2022-09-09 03:32 UTC by Rhett-Ying

## Description

fix for https://github.com/dmlc/dgl/issues/4515.
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2022-09-13 07:31 UTC, jermainewang requested changes

2022-09-13 07:31 UTC, jermainewang commented on tests/tools/test_dist_part.py
> +                      in_dir, partition_dir, out_dir, ip_config))
Use f-string could simplify the code.

2022-09-14 04:19 UTC, Rhett-Ying commented on tools/distpartitioning/data_proc_pipeline.py
> +                        help='timeout[seconds] for operations executed agains the process group')
it's extracted from `torch.distrbuted.init_process_group`.

2022-09-14 09:29 UTC, jermainewang commented on tools/distpartitioning/data_proc_pipeline.py
> +                        help='timeout[seconds] for operations executed against the process group')
```suggestion
                        help='timeout[seconds] for operations executed against the process group '
                             '(see torch.distributed.init_process_group)')
```

2022-09-14 09:29 UTC, jermainewang approved these changes

2022-09-15 07:28 UTC, merged