[WIP] Migration of Unary, Softmax, Matmul Ops
dmlc/dgl pull request #4616
Opened 2022-09-21 09:12 UTC by mufeili

## Description

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

2022-09-25 06:10 UTC, jermainewang requested changes

2022-09-25 06:10 UTC, jermainewang commented on tests/pytorch/mock_sparse/test_mm.py
> +    dense_result = A.adj.to_dense() @ X
I see these tests are using the internal members of `A`. The issue is that when we replace the implementation in the future, we need to change test codes too. Can you directly use `row` and `col` to construct ground truth result?

2022-09-26 08:19 UTC, mufeili commented on python/dgl/mock_sparse/matmul.py
> +def spmm(A1: Union[SparseMatrix, DiagMatrix], A2: Union[torch.Tensor, SparseMatrix, DiagMatrix])\
Updated

2022-09-26 08:19 UTC, mufeili commented on python/dgl/mock_sparse/matmul.py
> +def bspmm(A1: Union[SparseMatrix, DiagMatrix], A2: Union[torch.Tensor, SparseMatrix, DiagMatrix])\
Updated

2022-09-26 08:23 UTC, mufeili commented on python/dgl/mock_sparse/matmul.py
> +    assert val_dim == 1, f'Expect arg2.val to be a 1D tensor, got {val_dim}D'
Updated a bit and see if it is better to you now. `if + raise` are used when we dispatch the input arguments to different underlying ops depending on the type of the input arguments.

2022-09-26 08:24 UTC, mufeili commented on python/dgl/mock_sparse/matmul.py
> +def diag_diag(A1: DiagMatrix, A2: DiagMatrix) -> DiagMatrix:
Changed to `diag_diag_mm`

2022-09-26 15:56 UTC, jermainewang approved these changes

2022-09-26 15:57 UTC, jermainewang commented
The new logic is much cleaner. Nice job!

2022-09-27 05:19 UTC, mufeili commented on python/dgl/mock_sparse/matmul.py
> +    >>> result = A @ X
updated

2022-09-27 11:34 UTC, merged