[Dist] save shuffled node/edge ID mapping during graph partition
dmlc/dgl pull request #4625
Opened 2022-09-23 05:23 UTC by Rhett-Ying

## Description

Target on https://github.com/dmlc/dgl/issues/4359.
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2022-09-26 16:08 UTC, jermainewang requested changes

2022-09-26 16:08 UTC, jermainewang commented on python/dgl/distributed/partition.py
> +        Indicate whether to save original node IDs as node feature of partitions.
For bool type value, use "If True, xxxx" to describe usage, e.g.,
```
If True, save the original node IDs as node features of name ``dgl.ORIG_NID``.
```

2022-09-26 16:08 UTC, jermainewang commented on tools/dispatch_data.py
> +    parser.add_argument('--save-orig-nids', action='store_true', help='save original node IDs')
'Save original node IDs as node features of name dgl.ORIG_NID.'

2022-09-26 16:08 UTC, jermainewang commented on tools/dispatch_data.py
> +    parser.add_argument('--save-orig-eids', action='store_true', help='save original edge IDs')
same comment

2022-09-26 16:08 UTC, jermainewang commented on tools/distpartitioning/data_shuffle.py
> +from dgl import backend as F
No need to import other framework-agnostic backend. The code is PyTorch only.

2022-09-26 16:08 UTC, jermainewang commented on tools/distpartitioning/data_shuffle.py
> +            orig_nids = F.boolean_mask(graph_obj.ndata['orig_id'], mask)
Same question. Can we remove or reuse the old "orig_id"?

2022-09-26 16:08 UTC, jermainewang commented on python/dgl/distributed/partition.py
> +                node_feats[ntype + '/' + ORIG_NID] = F.boolean_mask(part.ndata['orig_id'],
If there are 10 node types, you will save 10 copies of ORIG_NIDs. However, you should only need one.

2022-09-27 07:20 UTC, Rhett-Ying commented
As discussed offline, we'd like to change the way of ID storage. I will file a new PR

2022-09-27 07:20 UTC, closed without merging