[Feature] Add bfloat16 (bf16) support
dmlc/dgl pull request #4648
Opened 2022-09-27 02:58 UTC by yaox12

## Description

Add bfloat16 support for CUDA >= 11.0.

1. Add bf16 specializations for supported functions.
2. Change the float type dispatcher from bits to real data types.
3. Make PyTorch custom autograd modules work with both bf16 and fp16.
4. Enable bf16 tests for `segment_mm` and `gather_mm`.

**Note**: `-DUSE_FP16` is removed. FP16 is enabled by default while BF16 is enabled for CUDA >= 11.0, which follows the PyTorch convention.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR

## Examples

1. Message-passing with bf16 is supported for CUDA >= 11.0 (even on older GPUs with SM < 80). For example, the following code works well on V100.
```python
>>> import torch
>>> import dgl
>>> import dgl.function as fn
>>> dev = torch.device('cuda')
>>> g = dgl.rand_graph(30, 100).to(dev)  # Create a graph on GPU w/ 30 nodes and 100 edges.
>>> g.ndata['h'] = torch.rand(30, 16).to(dev, torch.bfloat16)  # Create bf16 node features.
>>> g.edata['w'] = torch.rand(100, 1).to(dev, torch.bfloat16)  # Create bf16 edge features.
>>> # Use DGL's built-in functions for message passing on bf16 features.
>>> g.update_all(fn.u_mul_e('h', 'w', 'm'), fn.sum('m', 'x'))
>>> g.ndata['x'].dtype
torch.bfloat16
>>> g.apply_edges(fn.u_dot_v('h', 'x', 'hx'))
>>> g.edata['hx'].dtype
torch.bfloat16
```

2. AMP only works on GPUs with SM >= 80 and CUDA >= 11.0.

This also follows the PyTorch convention. See https://github.com/dmlc/dgl/issues/4333#issuecomment-1253277674.

2022-09-30 04:43 UTC, frozenbugs commented on src/array/cuda/bf16.cuh
> +__device__ __forceinline__ bool operator==(const __nv_bfloat16& lh, const __nv_bfloat16& rh) {
I think we are following Google C++ code style. 
Which advocate 80 characters line.
https://google.github.io/styleguide/cppguide.html#Line_Length

2022-09-30 04:44 UTC, frozenbugs commented
Thanks for the great work, even with several comment, this PR still hold high standard code quality :)
Another comment I would suggest you to do in the future is to avoid such a big PR, if possible, separate the refactoring and adding new lines of code such that it is easier to be reviewed.

2022-09-30 20:20 UTC, isratnisa requested changes
This is a huge effort. Thanks! Have you done any regression test? How is the performance compare to fp16? I have left a few comments about disabling CPU support for half precision. Otherwise, LGTM.

2022-09-30 23:15 UTC, ndickson-nvidia requested changes

2022-10-10 09:14 UTC, yaox12 commented on include/dgl/runtime/ndarray.h
> +#define BF16_ENABLED defined(CUDART_VERSION) && CUDART_VERSION >= 11000
Changed accordingly.

2022-10-10 09:14 UTC, yaox12 commented on src/array/cuda/utils.h
> +      out[tx] = weights ? weights[v] : static_cast<DType>(static_cast<double>(v));
Added a specialization for bfloat16.

2022-10-10 09:17 UTC, yaox12 commented on src/array/cpu/gather_mm.cc
> -template void GatherMM<kDGLCPU, int32_t, 16>(
Yes. In the current master branch, we either fall back to float32 or throw an error for half precision on CPU. I think it's OK to remove it.

2022-10-10 09:23 UTC, yaox12 commented
> Have you done any regression test?

Not yet. It seems I don't have the authentication to trigger regression tests, and I failed to run it locally.
 
> How is the performance compare to fp16?

For the AMP example in https://docs.dgl.ai/en/0.9.x/guide/mixed_precision.html, bf16 has a similar performance as fp16, both slightly faster than fp32. 
An advantage of bf16 is that it supports pure-bf16 training without AMP. Thus the example in https://github.com/dmlc/dgl/pull/4262 could converge with bf16 but not fp16.

2022-10-10 09:38 UTC, yaox12 commented on src/array/cuda/atomic.cuh
> +// half make sure we have half support
Update. This is a copy-paste typo. Should be "make sure we have bfloat16 support".

2022-10-10 09:38 UTC, yaox12 commented on src/array/cuda/atomic.cuh
> +  printf("Atomic operations are not supported for bfloat16 (BF16) "
Update accordingly.

2022-10-10 09:41 UTC, yaox12 commented on src/array/cuda/atomic.cuh
> +  printf("Atomic operations are not supported for bfloat16 (BF16) "
This is a device(GPU)-side error message, which doesn't support the `LOG` macro. So we just use `printf` as a workaround.

2022-10-11 02:47 UTC, frozenbugs commented on src/array/cuda/atomic.cuh
> +  printf("Atomic operations are not supported for bfloat16 (BF16) "
Looks like an AI to take in the future, not sure whether you are happy to own it or not, we can discuss it in the meeting.

2022-10-12 17:58 UTC, BarclayII commented on src/array/cuda/atomic.cuh
> +  printf("Atomic operations are not supported for bfloat16 (BF16) "
Could we move the check outside the device code though?

2022-11-04 10:23 UTC, isratnisa approved these changes

2022-11-06 11:48 UTC, merged