Parallel find edges
dmlc/dgl pull request #4878
Opened 2022-11-13 07:42 UTC by BarclayII

## Description
This parallelizes `find_edges`, which could mitigate the low CPU utilization in link prediction compared to node classification (#4357 ).

2022-11-14 08:22 UTC, jermainewang requested changes

2022-11-14 08:22 UTC, jermainewang commented on src/array/cpu/array_index_select.cc
> +      [idx_data, arr_len, ret_data, array_data] (size_t b, size_t e) {
Could you pls rename `b` and `e` to `begin` and `end`?

2022-11-14 09:25 UTC, frozenbugs approved these changes

2022-11-14 09:27 UTC, frozenbugs approved these changes

2022-11-15 07:48 UTC, jermainewang approved these changes

2022-11-15 07:48 UTC, merged