[Performance] Make IdHashMap parallel
dmlc/dgl pull request #4881
Opened 2022-11-14 04:30 UTC by BarclayII

## Description
`IdHashMap::Map` is executed sequentially.  So I make it parallelizable.  This should mitigate the low CPU utilization in distributed training (#4357 ) to some extent.

2022-11-14 08:22 UTC, jermainewang requested changes

2022-11-14 08:22 UTC, jermainewang commented on src/array/cpu/array_utils.h
> +        0, len, 1000, [=] (size_t b, size_t e) {
Please rename `b` and `e` to `begin` and `end`.

2022-11-14 09:16 UTC, frozenbugs approved these changes

2022-11-15 07:49 UTC, jermainewang approved these changes

2022-11-15 07:49 UTC, merged