[Example] Sparse Graph Transformer
dmlc/dgl pull request #5069
Opened 2022-12-26 08:28 UTC by rudongyu

## Description
close #5056 

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

2022-12-27 02:19 UTC, jermainewang commented on examples/sparse/graph_transformer.py
> +    dataset = CoraGraphDataset()
Maybe using a graph prediction dataset to be more real?

2022-12-27 05:57 UTC, mufeili commented on examples/sparse/graph_transformer.py
> +        pos_enc_size=2,
Does this have to be the same as in `laplacian_pe`? If so, consider passing it to both `laplacian_pe` and `GTModel` instead.

2022-12-27 06:34 UTC, mufeili commented on examples/sparse/graph_transformer.py
> +    def __init__(self, hidden_size=80, num_heads=8) -> None:
```suggestion
    def __init__(self, hidden_size=80, num_heads=8):
```

Better to be consistent, either include that for all modules or the other way

2022-12-27 06:41 UTC, mufeili commented on examples/sparse/graph_transformer.py
> +        val_acc, test_acc = evaluate(g, pred)
Missing `model.eval()`

2022-12-27 06:41 UTC, mufeili requested changes
Minor comments

2022-12-29 12:37 UTC, mufeili commented on examples/sparse/graph_transformer.py
> +from dgl.mock_sparse import bspmm, create_from_coo, mock_bsddmm as bsddmm
```suggestion
from dgl.sparse import bspmm, create_from_coo, mock_bsddmm as bsddmm
```
with #5088 merged

2023-01-03 03:00 UTC, jermainewang approved these changes
Nice!

2023-01-03 03:03 UTC, jermainewang commented
@rudongyu How long is the training and what accuracy does it get?

2023-01-03 03:24 UTC, rudongyu commented
> @rudongyu How long is the training and what accuracy does it get?

~75 secs for positional encoding computation and 5mins for training (50 epochs, Tesla T4).
Performance (ROC AUC): Val-79.35, Test-74.77

2023-01-03 15:01 UTC, mufeili commented on examples/sparse/graph_transformer.py
> +        A = dglsp.create_from_coo(dst, src, shape=(N, N))
```suggestion
        A = dglsp.from_coo(dst, src, shape=(N, N))
```
with #5093 merged

2023-01-04 03:29 UTC, mufeili approved these changes

2023-01-05 00:50 UTC, merged