[Sparse] Polish sparse matrix creation functions
dmlc/dgl pull request #5093
Opened 2022-12-30 08:26 UTC by mufeili

## Description

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [x] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2022-12-30 08:59 UTC, jermainewang requested changes

2022-12-30 08:59 UTC, jermainewang commented on dgl_sparse/src/python_binding.cc
> -  m.def("create_from_coo", &CreateFromCOO)
Rename C++ function to `FromCOO` too.

2023-01-03 04:44 UTC, mufeili commented on dgl_sparse/src/python_binding.cc
> -  m.def("create_from_coo", &CreateFromCOO)
done

2023-01-03 14:10 UTC, mufeili commented
@jermainewang I've updated the PR upon our discussion.

2023-01-03 14:54 UTC, jermainewang approved these changes

2023-01-03 14:59 UTC, merged