[Transform] Add SvdPE Transform Module
dmlc/dgl pull request #5121
Opened 2023-01-07 08:40 UTC by ZhenyuLU-Heliodore

## Description

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2023-01-09 19:04 UTC, rudongyu requested changes
1st round review

2023-01-11 16:02 UTC, ZhenyuLU-Heliodore commented on python/dgl/transforms/functional.py
> +    `Global Self-Attention as a Replacement for Graph Convolution
’We propose a form of positional encoding based on precalculated SVD of the graph structural matrices. We use the largest 𝑟 singular values and corresponding left and right singular vectors to form our positional encodings. ‘

2023-02-01 23:55 UTC, rudongyu commented
@dgl-bot

2023-02-02 09:50 UTC, rudongyu reviewed
some minor issues

2023-02-02 09:50 UTC, rudongyu commented on python/dgl/transforms/functional.py
> +    <https://arxiv.org/pdf/2108.03348.pdf>`__
add an empty line below

2023-02-02 09:50 UTC, rudongyu commented on python/dgl/transforms/module.py
> +    <https://arxiv.org/pdf/2108.03348.pdf>`__
add an empty line below

2023-02-02 09:50 UTC, rudongyu commented on python/dgl/transforms/module.py
> +        where :math:`N` is number of nodes in :attr:`g`.
```suggestion
        where :math:`N` is the number of nodes in :attr:`g`.
```

2023-02-06 07:03 UTC, rudongyu approved these changes

2023-02-06 07:04 UTC, rudongyu commented
@dgl-bot

2023-02-08 04:29 UTC, merged