Add zinc
dmlc/dgl pull request #5428
Opened 2023-03-06 14:53 UTC by ZhenyuLU-Heliodore

## Description

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2023-03-07 07:09 UTC, rudongyu commented
@dgl-bot

2023-03-08 01:38 UTC, rudongyu requested changes

2023-03-08 01:38 UTC, rudongyu commented on docs/source/api/python/dgl.data.rst
> +    ZINCDataset
Note that ZINC is for graph prediction.

2023-03-08 01:38 UTC, rudongyu commented on python/dgl/data/zinc.py
> +    r""" ZINC dataset for graph regression task.
```suggestion
    r""" ZINC dataset for the graph regression task.
```

2023-03-08 01:38 UTC, rudongyu commented on python/dgl/data/zinc.py
> +   >>> training_set = ZINCDataset(mode="train")
```suggestion
   >>> from dgl.data import ZINCDataset

   >>> training_set = ZINCDataset(mode="train")
```

2023-03-08 01:38 UTC, rudongyu commented on python/dgl/data/zinc.py
> +   """
please check the indent of documentation.

2023-03-08 01:38 UTC, rudongyu commented on tests/python/common/data/test_data.py
> +        assert dataset2.num_atom_types == 28
The static property of the dataset don't need to be tested.

2023-03-12 10:40 UTC, rudongyu reviewed
Good job, thanks. please fix issues corresponding to the new comments.

2023-03-12 10:40 UTC, rudongyu commented on python/dgl/data/zinc.py
> +            - ``edata['feat']``: Type of bonds as edge features
```suggestion
            - ``edata['feat']``: Types of bonds as edge features
```

2023-03-12 10:40 UTC, rudongyu commented on tests/python/common/data/test_data.py
> +        assert label.shape == 1
Please recheck the assertion on label shape (label.shape returns a torch.Size object).

2023-03-15 10:20 UTC, frozenbugs commented on python/dgl/data/zinc.py
> +
nit: redundant blank line.

2023-03-21 10:25 UTC, frozenbugs commented
LGTM, @rudongyu feel free to merge.

2023-03-22 02:59 UTC, rudongyu commented
@dgl-bot

2023-03-22 05:21 UTC, rudongyu commented
@dgl-bot

2023-03-22 06:32 UTC, rudongyu commented
@dgl-bot

2023-03-22 07:41 UTC, rudongyu commented
@dgl-bot

2023-03-22 08:48 UTC, rudongyu approved these changes

2023-03-22 08:49 UTC, rudongyu commented
@dgl-bot

2023-03-22 10:04 UTC, merged