[Sparse] Compact C++ API
dmlc/dgl pull request #6334
Opened 2023-09-15 02:33 UTC by xiangyuzhi

## Description
Add C++ API for compact operation.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes

2023-09-15 06:30 UTC, czkkkkkk requested changes

2023-09-15 06:30 UTC, czkkkkkk commented on dgl_sparse/include/sparse/macro.h
Move `marco.h` and `matrix_ops_impl.h` to `src` since they are implementation files.

2023-09-15 06:30 UTC, czkkkkkk commented on dgl_sparse/include/sparse/macro.h
> + * Dispatch according to device:
```suggestion
 * Dispatch an operator to a templated implementation function according to its device:
```

2023-09-15 06:30 UTC, czkkkkkk commented on dgl_sparse/include/sparse/matrix_ops.h
> + * @param mat The sparse matrix to be relabeled.
```suggestion
 * @param mat The sparse matrix to be compacted.
```

2023-09-15 06:30 UTC, czkkkkkk commented on dgl_sparse/include/sparse/matrix_ops.h
> + * @param dim The dimension to relabel. Should be 0 or 1. Use 0 for row-wise
```suggestion
 * @param dim The dimension to compact. Should be 0 or 1. Use 0 for row-wise
```

2023-09-15 06:30 UTC, czkkkkkk commented on dgl_sparse/include/sparse/matrix_ops.h
> + *        relabeling and 1 for column-wise relabeling.
```suggestion
 *        compaction and 1 for column-wise compaction.
```

2023-09-15 06:30 UTC, czkkkkkk commented on dgl_sparse/include/sparse/matrix_ops.h
> + *        should be placed at the beginning of the relabeled dimension.
```suggestion
 *        should be placed at the beginning of the compact dimension.
```

2023-09-15 06:30 UTC, czkkkkkk commented on dgl_sparse/include/sparse/matrix_ops.h
> + * @return A tuple containing the relabeled sparse matrix and the index mapping
```suggestion
 * @return A tuple containing the compacted sparse matrix and the index mapping
```

2023-09-15 06:30 UTC, czkkkkkk commented on dgl_sparse/include/sparse/matrix_ops.h
> +    const c10::intrusive_ptr<SparseMatrix>& mat, uint64_t dim,
```suggestion
    const c10::intrusive_ptr<SparseMatrix>& mat, int64_t dim,
```
Seems that Pytorch FFI doesn't have `uint64_t`.

2023-09-15 06:30 UTC, czkkkkkk commented on dgl_sparse/src/matrix_ops.cc
> +std::tuple<c10::intrusive_ptr<SparseMatrix>, torch::Tensor> Compact(
`.cc` files don't need documentation.

2023-09-15 09:17 UTC, czkkkkkk approved these changes

2023-09-15 09:17 UTC, czkkkkkk commented on dgl_sparse/src/macro.h
> +#define DGL_SPARSE_XPU_SWITCH(val, XPU, op, ...)                \
```suggestion
#define DGL_SPARSE_XPU_SWITCH(device, XPU, op, ...)                \
```

2023-09-15 09:17 UTC, czkkkkkk commented on dgl_sparse/src/macro.h
> +#define DGL_SPARSE_ID_TYPE_SWITCH(val, IdType, op, ...)         \
```suggestion
#define DGL_SPARSE_ID_TYPE_SWITCH(dtype, IdType, op, ...)         \
```

2023-09-15 09:17 UTC, czkkkkkk commented on dgl_sparse/src/matrix_ops_impl.h
> + */
This comment is redundant considering the `Compact` interface. We can safely remove it since it is for internal implementation.

2023-09-18 09:29 UTC, frozenbugs approved these changes

2023-09-18 12:12 UTC, merged