[DeprecationWarning] Fixing the warnings appearing in `test_traversal.py::test_bfs`.
dmlc/dgl pull request #7484
Opened 2024-06-26 19:38 UTC by drivanov

## Description

The following two sets of warnings  that appear in `test_traversal.py::test_bfs` have been fixed:
```
./../../usr/local/lib/python3.10/dist-packages/dgl/graphbolt/base.py:80
  /usr/local/lib/python3.10/dist-packages/dgl/graphbolt/base.py:80: DeprecationWarning: torch.library.impl_abstract was renamed to torch.library.register_fake. Please use that instead; we will remove torch.library.impl_abstract in a future version of PyTorch.
    @torch.library.impl_abstract("graphbolt::expand_indptr")

tests/python/common/test_traversal.py::test_bfs[idtype0]
tests/python/common/test_traversal.py::test_bfs[idtype1]
  /usr/local/lib/python3.10/dist-packages/networkx/utils/backends.py:812: DeprecationWarning:
 
  random_tree is deprecated and will be removed in NX v3.4
  Use random_labeled_tree instead.
    return self.orig_func(*args, **kwargs)
```

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [x] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

## Changes

2024-06-29 13:48 UTC, mfbalin commented on python/dgl/graphbolt/base.py
> +    @torch.library.register_fake("graphbolt::expand_indptr")
```suggestion
    @torch.library.impl_abstract("graphbolt::expand_indptr")
```

2024-06-29 13:49 UTC, mfbalin requested changes

2024-06-29 13:49 UTC, mfbalin commented on python/dgl/graphbolt/base.py
> +    @torch.library.register_fake("graphbolt::expand_indptr")
The backwards compatible change is in #7493.

2024-07-01 03:01 UTC, frozenbugs commented
@dgl-bot

2024-07-01 04:54 UTC, frozenbugs approved these changes

2024-07-01 04:54 UTC, frozenbugs commented
@dgl-bot

2024-07-01 07:02 UTC, merged