[DistGB] save as graphbolt graph directly after partition test case
dmlc/dgl pull request #7724
Opened 2024-08-20 09:37 UTC by CfromBU

modify the test_partiton.py

2024-08-21 07:29 UTC, CfromBU commented
order:
https://github.com/dmlc/dgl/pull/7724 partition test case
https://github.com/dmlc/dgl/pull/7727 partition
https://github.com/dmlc/dgl/pull/7728 dist partition
https://github.com/dmlc/dgl/pull/7690 dist partition test case

2024-08-21 09:05 UTC, Rhett-Ying requested changes

2024-08-21 09:05 UTC, Rhett-Ying commented on tests/distributed/test_partition.py
> +            for name in ["labels", "feats"]:
why not verify via `verify_graph_feats()`?

2024-08-21 09:05 UTC, Rhett-Ying commented on tests/distributed/test_partition.py
> +            # Verify the mapping between the reshuffled IDs and the original IDs.
is such check covered in `verify_hetero_graph()`?

2024-08-22 07:33 UTC, CfromBU commented on python/dgl/distributed/partition.py
> +            dtype = F.dtype(graph.node_attributes["inner_node"])
before `_get_inner_node_mask` is called, `graph` will be checked if "inner_node" exists. And I added an assert in `_get_inner_node_mask`

2024-08-22 07:34 UTC, CfromBU commented on python/dgl/distributed/partition.py
> +            dtype = F.dtype(graph.edge_attributes["inner_edge"])
I have remove the ditto.

2024-08-22 07:35 UTC, CfromBU commented on tests/distributed/test_partition.py
> +    if not use_graphbolt:
Ok, I have replace the duplicate codes.

2024-08-22 07:52 UTC, CfromBU commented on tests/distributed/test_partition.py
> +            eid_type = F.gather_row(part.edge_attributes[dgl.EID], eid)
`eid_type` is used to build `eids`, which stores `eids` according to its etype. But `eid_type` is used to connect to the `eids` `etype_arr`'s order. I copied it from source code but the variable `eid_type` doesn't have an appropriate name, so I rename it to `eid_arr` to emphasize its connection with `eid_type`.

2024-08-23 08:13 UTC, CfromBU commented
I modified the function in test case that relevant to graphbolt, but didn't change the function about DGLGraph.

2024-08-26 07:35 UTC, Rhett-Ying requested changes

2024-08-26 07:35 UTC, Rhett-Ying commented on python/dgl/distributed/partition.py
> +    assert "inner_node" in ndata, '"inner_node" is not nodes\' data'
use `""` instead `'` for the out-most wrapper.

2024-08-26 07:35 UTC, Rhett-Ying commented on python/dgl/distributed/partition.py
> +        dtype = F.dtype(edata["inner_edge"])
assert `inner_edge`?

2024-08-26 07:35 UTC, Rhett-Ying commented on python/dgl/distributed/partition.py
> +    assert "num_parts" in part_metadata, "num_parts does not exist."
this huge code block is duplicated?

2024-08-26 07:35 UTC, Rhett-Ying commented on tests/distributed/test_partition.py
> +import dgl.sparse as dglsp
is it possible to avoid import dgl sparse?

2024-08-27 07:32 UTC, Rhett-Ying commented on tests/distributed/test_partition.py
> +        if debug_mode:
ditto

2024-08-27 07:32 UTC, Rhett-Ying commented on tests/distributed/test_partition.py
> +            # TODO verify mapping IDs
TODO?

2024-08-28 05:52 UTC, Rhett-Ying commented
@CfromBU pls fix the lint check failure

2024-09-04 12:54 UTC, Rhett-Ying commented on python/dgl/distributed/partition.py
> +    ndata = graph.node_attributes if use_graphbolt else graph.ndata
we could check `isinstance(graph, gb.FusedCSCSamplingGraph)`, then we don't need `use_graphbolt`

2024-09-04 12:54 UTC, Rhett-Ying commented on tests/distributed/test_partition.py
> +    ndata = part_g.node_attributes if use_graphbolt else part_g.ndata
ditto, check isinstance()?

2024-09-04 12:54 UTC, Rhett-Ying commented on tests/distributed/test_partition.py
> +        eids[etype].append(F.boolean_mask(eid_arr, etype_arr == etype_id))
where is `eids` defined? and used? seems not used at all?

2024-09-04 12:54 UTC, Rhett-Ying commented on tests/distributed/test_partition.py
> +    if store_inner_node:
this body looks weird. How is the `store_inner_node/edge` flag related to the check here? In intuition, this flag is about `partition.ndadta['inner_node/edge']. but it's not directly used here.

2024-09-04 12:54 UTC, Rhett-Ying commented on tests/distributed/test_partition.py
> -            else:
why remove these lines? do they fail the testcase? if not , keep it.

2024-09-04 12:54 UTC, Rhett-Ying commented on tests/distributed/test_partition.py
> +def _verify_builded_id_gb(part_sizes, gpb):
`built`? or `constructed`?

2024-09-05 06:02 UTC, Rhett-Ying commented on tests/distributed/test_partition.py
> +    return eids
It's weird that a verify function returns data. As it's tests, let's tolerate it.

2024-09-05 06:02 UTC, Rhett-Ying approved these changes

2024-09-05 06:08 UTC, merged